rm -rf $BULLETSIM_BUILD_DIR
mkdir $BULLETSIM_BUILD_DIR

mkdir -p $BULLETSIM_BUILD_DIR/debug
cd $BULLETSIM_BUILD_DIR/debug
cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=OFF $BULLETSIM_SOURCE_DIR

mkdir -p $BULLETSIM_BUILD_DIR/release
cd $BULLETSIM_BUILD_DIR/release
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF $BULLETSIM_SOURCE_DIR
